baseurl = "https://madduci.netlify.com"
repourl = "https://github.com/madduci/micheleadduci.net"
title = "Michele Adduci"

copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."

theme = "hugo-coder"

languageCode = "en-us"
defaultcontentlanguage = "en"

canonifyurls = true
enableEmoji = false
enableRobotsTXT = true
googleAnalytics = ""

preserveTaxonomyNames = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[markup]
  [markup.goldmark.renderer]
      unsafe = true

[Permalinks]
 posts = "posts/:year/:filename/"

[author]
    name = "Michele Adduci"

[params]
    author = "madduci"
    description = "Michele Adduci - Personal Website"
    keywords = "blog,engineer,personal"
    info = "Computer Engineer"
    avatarurl = "images/avatar.jpg"

    dateformat = "January 2, 2006"

    hideCredits = false
    hideCopyright = false
    since = 2009

    rtl = false

    colorscheme = "light"

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = []

    # Custom JS
    custom_js = []

    license= '<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="me noopener">CC BY-NC 4.0</a>'

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
    name = "Github"
    icon = "icon-github-circled-alt2"
    weight = 1
    url = "https://github.com/madduci/"
[[params.social]]
    name = "Twitter"
    icon = "icon icon-twitter"
    weight = 2
    url = "https://twitter.com/m_adduci/"
[[params.social]]
    name = "LinkedIn"
    icon = "icon icon-linkedin"
    weight = 3
    url = "https://www.linkedin.com/in/adduci/"
[[params.social]]
    name = "StackOverflow"
    icon = "icon icon-stackoverflow"
    weight = 4
    url = "https://stackoverflow.com/story/adduci"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[languages]
    [languages.en]
        languagename = "English"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "About"
            weight = 1
            url = "about/"

            [[languages.en.menu.main]]
            name = "Blog"
            weight = 2
            url = "posts/"

            [[languages.en.menu.main]]
            name = "Contact"
            weight = 3
            url = "contact/"

            [[languages.en.menu.main]]
            name = "Policy"
            weight = 4
            url = "policy/"
